library(shiny)
library(bslib)
library(leaflet)
library(dplyr)

# ---- Load pre-processed forecast data (generated by prep_app_data.R) ----
app_data       <- readRDS("data/app_data.rds")
prob_data      <- app_data$prob_data
all_points     <- app_data$all_points
tcz_boundary        <- app_data$tcz_boundary
pastoral_boundaries <- app_data$pastoral_boundaries
initial_bounds      <- app_data$initial_bounds
years          <- app_data$years
start_year     <- if (!is.null(app_data$start_year)) app_data$start_year else min(years)
n_sims         <- app_data$n_sims
updated        <- format(app_data$updated, "%B %Y")

# ---- Colour palette ----
pal <- colorBin(
  palette = "YlOrRd",
  domain  = c(0, 1),
  bins    = c(0, 0.2, 0.4, 0.6, 0.8, 1),
  na.color = "transparent"
)

# ---- UI ----
ui <- page_sidebar(
  title  = "Cane Toad Forecast",
  theme  = bs_theme(bootswatch = "flatly"),
  window_title = "Cane Toad Forecast | toadfree.zone",

  sidebar = sidebar(
    width = 310,

    sliderInput(
      "year", label = "Year",
      min = min(years), max = max(years),
      value = min(years), step = 1, sep = "",
      animate = animationOptions(interval = 900, loop = FALSE)
    ),

    p(class = "text-muted small",
      "Each dot is a waterpoint. Colour shows the probability it has been",
      "colonised by toads by the selected year, based on", n_sims,
      "simulation replicates. Click any dot for details."
    ),

    hr(),

    tags$a(
      href = "https://www.surveymonkey.com/r/BJ8YV9H",
      target = "_blank",
      class = "btn btn-primary w-100 mb-3",
      icon("envelope"), " Get annual forecast updates"
    ),

    hr(),

    p(class = "text-muted small",
      "Forecast last updated: ", strong(updated), ".",
      br(),
      tags$a(href = "https://toadfree.zone", target = "_blank",
             "toadfree.zone")
    )
  ),

  card(
    full_screen = TRUE,
    padding = 0,
    leafletOutput("map", height = "780px")
  )
)

# ---- Server ----
server <- function(input, output, session) {

  # The slider's value isn't available on the very first server pass under
  # shinylive/webR (R renders before the browser's inputs arrive), so fall back
  # to the first year rather than passing NULL into the filter below.
  current_year <- reactive({
    y <- input$year
    if (length(y) != 1 || is.na(y)) min(years) else y
  })

  # Draw the two waterpoint layers for a given year onto either the initial
  # `leaflet()` map or a `leafletProxy()`. Both accept the same add*/clearGroup
  # verbs, so one helper covers both call sites.
  #
  # The initial draw MUST happen inside renderLeaflet() (below), not only from an
  # observer: a leafletProxy() call can race the map widget's first render and be
  # dropped, which under shinylive/webR happens every time -- the map then shows
  # boundaries but no points until the slider is touched.
  draw_points <- function(map, yr) {
    d <- prob_data[prob_data$year == yr & prob_data$prob > 0, , drop = FALSE]

    map |>
      # Grey background dots (every waterpoint), year-specific popup
      clearGroup("background") |>
      addCircleMarkers(
        data        = all_points,
        lng         = ~lon,
        lat         = ~lat,
        radius      = 3,
        fillColor   = "#aaaaaa",
        fillOpacity = 0.4,
        stroke      = FALSE,
        group       = "background",
        popup       = paste0(
          "<b>Waterpoint</b><br>",
          "Probability colonised by <b>", yr, "</b>: <b>0%</b>"
        )
      ) |>
      clearGroup("points") |>
      addCircleMarkers(
        data        = d,
        lng         = ~lon,
        lat         = ~lat,
        radius      = 4,
        fillColor   = ~pal(prob),
        fillOpacity = 0.85,
        stroke      = FALSE,
        group       = "points",
        popup       = ~paste0(
          "<b>Waterpoint</b><br>",
          "Probability colonised by <b>", yr, "</b>: ",
          "<b>", round(prob * 100), "%</b><br>",
          ifelse(mean_arrival <= start_year,
                 paste0("Colonised since: <b>", mean_arrival, "</b>"),
                 paste0("Median expected arrival year: <b>", mean_arrival, "</b>"))
        )
      )
  }

  output$map <- renderLeaflet({
    leaflet() |>
      addProviderTiles(
        "Esri.WorldTopoMap",
        options = providerTileOptions(opacity = 0.75)
      ) |>

      addPolygons(
        data        = tcz_boundary,
        color       = "#cc0000",
        weight      = 2,
        fillOpacity = 0.05,
        label       = "Toad Containment Zone",
        group       = "TCZ Boundary"
      ) |>
      addPolygons(
        data        = pastoral_boundaries,
        color       = "#1a6faf",
        weight      = 1,
        fillOpacity = 0.05,
        group       = "Pastoral Boundaries"
      ) |>
      addLegend(
        position = "bottomright",
        pal      = pal,
        values   = c(0, 1),
        title    = "Probability of<br>toad arrival",
        opacity  = 0.9
      ) |>
      addLayersControl(
        overlayGroups = c("TCZ Boundary", "Pastoral Boundaries"),
        options = layersControlOptions(collapsed = FALSE)
      ) |>
      fitBounds(
        lng1 = initial_bounds$lng1,
        lat1 = initial_bounds$lat1,
        lng2 = initial_bounds$lng2,
        lat2 = initial_bounds$lat2
      ) |>
      draw_points(isolate(current_year()))
  })

  # Redraw the point layers whenever the year changes. clearGroup() makes this
  # idempotent, so the first run (harmlessly re-drawing what renderLeaflet already
  # painted, or correcting it once the real slider value arrives) is fine.
  observe({
    draw_points(leafletProxy("map"), current_year())
  })
}

shinyApp(ui, server)
